### ISSUE TITLE
Problems with v4.0.0

### ISSUE THREAD

**Issue by AaronKutch** [gabriela-tomazzi/birdTheme#1]
Hello, I use this theme a lot and noticed that v4.0.0 changed everything today. I would say that the colors are easier on the eyes in general, but there are a few problems with the balance. The lightness of comments is too close to that of the background.
Also, seems to me that some dimension was lost; there is a pair of colors that were made the same brown (some keywords and function names in Rust). I think I see why you would make them the same, but I think you should make them different enough to be distinguishable.

**Comment by AaronKutch** [comment]
another thing is that the selection foreground is too close to the background, see how hard it is to see "Open File"
![image](https://user-images.githubusercontent.com/32419308/134744800-e3ad37c4-9c4e-4d24-a9fe-2b5ea0887487.png)

**Comment by gabriela-tomazzi** [comment]
Sorry for the problems the update caused, I didn't expect someone to use my
themes in a daily basis, they are kinda of experimental for me, if you want
I can give you a copy of all other versions so you can install them, and I
will be updating v4.0.0 tomorrow. Thank you for the help in making it a
better theme.

**Comment by gabriela-schuster** [comment]
Thank you for the feedback, I added some borders to help with all the backgrounds being the same colors, and improved the contrast in selections, inputs and buttons a bit, about the rust syntax, it's hard for me to visualize what is not distinguishable, if you could send me a code example it would be really helpful.

Another thing is that you can use the v3.0.0, it's in this repository, just download it and `$ code --install-extension bird-3.1.0.vsix` on the same directory of the file.

**Comment by AaronKutch** [comment]
In this other theme, see how the color of `pub const fn` is different from `widening....`
![image](https://user-images.githubusercontent.com/32419308/134752542-0f1a862c-8cdc-4367-a5ba-e3707fffc7d0.png)
and here it is practically indistinguishable
![image](https://user-images.githubusercontent.com/32419308/134752566-f1ce8abe-45ad-4dfe-a994-104837ffe8e5.png)
The comment colors and selections are better now

**Comment by AaronKutch** [comment]
I'm looking at the old theme, and I'm thinking the brightness of the foreground except for the keywords (so now there would be a difference) should be increased. v4.0 needs a little more contrast between foreground and background.

**Comment by AaronKutch** [comment]
Edit: disregard my deleted comment about the contrast, I discovered my monitor settings were not standard and I was applying two layers of comfort view

Or maybe it is my separate monitors that are making illusions. The contrast is actually similar, I think it looks good except one of the keyword or function browns needs to be tweaked.

**Comment by AaronKutch** [comment]
While I'm talking with someone who is good at color themes, I thought I would share this set of 8 foregrounds colors in case you found it useful (I don't intend this for bird). I designed this set using CIELAB to get similar brightnesses and maximize apparent hue distance while still being colorblind friendly. It works with one gray, one blue, two from cyan to green, and 4 from yellow to purple. You can see 1-1-2-4 and 1-2-2-2-1 dichotomies going on.
![image](https://user-images.githubusercontent.com/32419308/134753199-d9bf1531-8c2d-4d3f-a32a-746e887a11fd.png)

**Comment by gabriela-schuster** [comment]
Just updated the rust function name to another color, if there's anything that isn't 'popping out' as much as it should be, send me a screenshot and I will update it as soon as possible.

About the colors, I'm not a designer, I just wanted something easy on eyes, all the themes I was using were causing discomfort after some time, that's why I change the actual colors so much, but I think this will be a definitive color scheme, suggestions are very welcome.

**Comment by AaronKutch** [comment]
thank you very much
